services:
  database:
    command: "--default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci"
    image: mysql:8.0.33
    environment:
        - "MYSQL_ROOT_PASSWORD=khanh123"
        - "MYSQL_DATABASE=cloudy"
    volumes:
        - db_mysql:/var/lib/mysql
    ports:
        - "33069:3306"

volumes:
  db_mysql: